import type { Project } from "@/lib/types";

const installChecklist = () => [
  { id: "ck1", label: "Confirm power source with customer", done: false },
  { id: "ck2", label: "Set up ladder safely + spotter", done: false },
  { id: "ck3", label: "Inspect & test light strings", done: false },
  { id: "ck4", label: "Install roofline clips", done: false },
  { id: "ck5", label: "Hang lights + secure connections", done: false },
  { id: "ck6", label: "Tree wrap (if applicable)", done: false },
  { id: "ck7", label: "Test full system after dark check", done: false },
  { id: "ck8", label: "Customer walkthrough + sign-off", done: false },
  { id: "ck9", label: "Clean site + collect packaging", done: false },
];

const takedownChecklist = () => [
  { id: "ck1", label: "Unplug + power down system", done: false },
  { id: "ck2", label: "Set up ladder safely + spotter", done: false },
  { id: "ck3", label: "Remove roofline strands", done: false },
  { id: "ck4", label: "Remove clips + tree wrap", done: false },
  { id: "ck5", label: "Coil + label customer's set (if owned)", done: false },
  { id: "ck6", label: "Inspect for damage + photo report", done: false },
  { id: "ck7", label: "Load truck + return to shop", done: false },
];

const repairChecklist = () => [
  { id: "ck1", label: "Diagnose reported issue", done: false },
  { id: "ck2", label: "Replace failed strand / fuse", done: false },
  { id: "ck3", label: "Test full circuit", done: false },
  { id: "ck4", label: "Customer sign-off", done: false },
];

export const projects: Project[] = [
  {
    id: "proj-001",
    customerId: "cust-roberts",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-05-25",
    takedownDate: "2027-01-08",
    crewSize: 2,
    estimatedHours: 4.5,
    packageType: "Classic Warm White",
    sqft: 2400,
    price: 1850,
    notes: "Returning customer — 3rd season. Repeat install with last year's plan.",
    specialInstructions: "Power from west garage outlet. Customer has extension cord ready.",
    assignedEmployeeIds: ["emp-jordan", "emp-marcus"],
    scheduledStart: "2026-05-25T09:00:00",
    checklist: installChecklist(),
    createdAt: "2026-05-10T14:22:00",
  },
  {
    id: "proj-002",
    customerId: "cust-tremblay",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-05-25",
    takedownDate: "2027-01-12",
    crewSize: 2,
    estimatedHours: 5,
    packageType: "Multicolor Pro",
    sqft: 1800,
    price: 1480,
    notes: "Cool whites on roof, multicolor on the two spruces out front.",
    specialInstructions: "Watch icy patches near south walkway. River-facing.",
    assignedEmployeeIds: ["emp-jordan", "emp-marcus"],
    scheduledStart: "2026-05-25T14:00:00",
    checklist: installChecklist(),
    createdAt: "2026-05-11T10:08:00",
  },
  {
    id: "proj-003",
    customerId: "cust-okafor",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-05-26",
    takedownDate: "2027-01-09",
    crewSize: 3,
    estimatedHours: 7,
    packageType: "C9 Premium",
    sqft: 3400,
    price: 2680,
    notes: "Large home on Wellington Crescent. Roofline + two evergreens + porch wrap.",
    specialInstructions: "Heritage home — no nails. Use clips only.",
    assignedEmployeeIds: ["emp-priya", "emp-alex", "emp-sam"],
    scheduledStart: "2026-05-26T08:30:00",
    checklist: installChecklist(),
    createdAt: "2026-05-08T16:45:00",
  },
  {
    id: "proj-004",
    customerId: "cust-friesen",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-05-27",
    takedownDate: "2027-01-15",
    crewSize: 2,
    estimatedHours: 5.5,
    packageType: "C9 Premium",
    sqft: 3100,
    price: 2350,
    notes: "Repeat customer. Same plan as last year.",
    specialInstructions: "Customer is meticulous — leave a copy of the install map.",
    assignedEmployeeIds: ["emp-priya", "emp-alex"],
    scheduledStart: "2026-05-27T09:00:00",
    checklist: installChecklist(),
    createdAt: "2026-05-12T11:30:00",
  },
  {
    id: "proj-005",
    customerId: "cust-nguyen",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-05-28",
    takedownDate: "2027-01-12",
    crewSize: 2,
    estimatedHours: 4,
    packageType: "Classic Warm White",
    sqft: 1750,
    price: 1380,
    notes: "First-time customer — referral from Tremblay.",
    assignedEmployeeIds: ["emp-jordan", "emp-tyler"],
    scheduledStart: "2026-05-28T10:00:00",
    checklist: installChecklist(),
    createdAt: "2026-05-14T09:12:00",
  },
  {
    id: "proj-006",
    customerId: "cust-wilson",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-05-29",
    takedownDate: "2027-01-09",
    crewSize: 2,
    estimatedHours: 4.5,
    packageType: "Classic Warm White",
    sqft: 2050,
    price: 1680,
    notes: "Corner lot St. Vital. Repeat customer.",
    specialInstructions: "Avoid east-side bedroom window — child sleeps early.",
    assignedEmployeeIds: ["emp-priya", "emp-sam"],
    scheduledStart: "2026-05-29T09:30:00",
    checklist: installChecklist(),
    createdAt: "2026-05-11T15:18:00",
  },
  {
    id: "proj-007",
    customerId: "cust-armstrong",
    status: "scheduled",
    serviceType: "takedown",
    installDate: "2026-06-01",
    crewSize: 2,
    estimatedHours: 3,
    packageType: "Custom",
    sqft: 2200,
    price: 480,
    notes: "Late takedown — customer was hosting visitors and left lights up.",
    assignedEmployeeIds: ["emp-marcus", "emp-tyler"],
    scheduledStart: "2026-06-01T08:00:00",
    checklist: takedownChecklist(),
    createdAt: "2026-05-18T08:00:00",
  },
  {
    id: "proj-008",
    customerId: "cust-vanwell",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-06-03",
    takedownDate: "2027-01-14",
    crewSize: 2,
    estimatedHours: 4,
    packageType: "Multicolor Pro",
    sqft: 1700,
    price: 1380,
    notes: "Repeat customer. Adding garland on porch railing this year.",
    specialInstructions: "Extra greenery garland — already in shop labelled VAN-WEL.",
    assignedEmployeeIds: ["emp-jordan", "emp-alex"],
    scheduledStart: "2026-06-03T10:00:00",
    checklist: installChecklist(),
    createdAt: "2026-05-15T13:42:00",
  },
  {
    id: "proj-009",
    customerId: "cust-singh",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-06-05",
    takedownDate: "2027-01-13",
    crewSize: 3,
    estimatedHours: 6.5,
    packageType: "C9 Premium",
    sqft: 2900,
    price: 2240,
    notes: "Two-story Tuxedo home. Roofline + four bushes + tree wrap.",
    assignedEmployeeIds: ["emp-priya", "emp-marcus", "emp-tyler"],
    scheduledStart: "2026-06-05T08:30:00",
    checklist: installChecklist(),
    createdAt: "2026-05-16T11:00:00",
  },
  {
    id: "proj-010",
    customerId: "cust-davies",
    status: "scheduled",
    serviceType: "repair",
    installDate: "2026-05-26",
    crewSize: 1,
    estimatedHours: 1.5,
    packageType: "Classic Warm White",
    sqft: 0,
    price: 180,
    notes: "One strand on north roofline is out. Repair under our season warranty.",
    specialInstructions: "Bring spare 25ft warm-white strand + spare fuses.",
    assignedEmployeeIds: ["emp-sam"],
    scheduledStart: "2026-05-26T13:00:00",
    checklist: repairChecklist(),
    createdAt: "2026-05-20T17:25:00",
  },
  {
    id: "proj-011",
    customerId: "cust-okafor",
    status: "scheduled",
    serviceType: "takedown",
    installDate: "2026-06-08",
    crewSize: 2,
    estimatedHours: 3.5,
    packageType: "C9 Premium",
    sqft: 3400,
    price: 540,
    notes: "Late takedown — customer was traveling.",
    assignedEmployeeIds: ["emp-priya", "emp-alex"],
    scheduledStart: "2026-06-08T09:00:00",
    checklist: takedownChecklist(),
    createdAt: "2026-05-19T14:10:00",
  },
  {
    id: "proj-012",
    customerId: "cust-armstrong",
    status: "scheduled",
    serviceType: "install",
    installDate: "2026-06-10",
    takedownDate: "2027-01-15",
    crewSize: 2,
    estimatedHours: 4.5,
    packageType: "Multicolor Pro",
    sqft: 2150,
    price: 1720,
    notes: "Upgrade from last year — adding two evergreens.",
    assignedEmployeeIds: ["emp-jordan", "emp-tyler"],
    scheduledStart: "2026-06-10T09:00:00",
    checklist: installChecklist(),
    createdAt: "2026-05-21T10:45:00",
  },
];

export function getProject(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}
